"""Init

Revision ID: 220239164755
Revises: 
Create Date: 2023-05-01 21:21:45.638539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '220239164755'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
