"""Update

Revision ID: 464840c93300
Revises: e51b192d2b4d
Create Date: 2023-05-07 22:06:53.935843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464840c93300'
down_revision = 'e51b192d2b4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
